# Generated by Django 5.1.6 on 2025-02-24 08:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firebase_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FCMToken",
            new_name="FCMTokens",
        ),
    ]
