# Generated by Django 5.1.6 on 2025-03-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firebase_app", "0003_notificationtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fcmtokens",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="fcmtokens",
            name="token",
        ),
        migrations.RemoveField(
            model_name="fcmtokens",
            name="user",
        ),
        migrations.AddField(
            model_name="fcmtokens",
            name="fcm_token",
            field=models.CharField(default="null", max_length=99999999, unique=True),
        ),
    ]
